### ISSUE TITLE
Окно регистрации пользователя

### ISSUE THREAD

**Issue by alekseynemiro** [alekseynemiro/MoneyBook#27]
Сделать форму создания нового пользователя. 

_Вполне возможно, что эту форму можно объединить с [формой аутентификации](https://github.com/alekseynemiro/MoneyBook/issues/25), просто расширив функционал последней._

Назвать форму можно: **NewUser** или **Registration**.
Форма должна запускаться  из окна аутентификации, по требованию пользователя.

Размер формы должен быть фиксированным. Пользователь не должен иметь возможность менять размер окна.

Кнопки сворачивания (**minimized**) и развертывания (**maximized**) должны отсутствовать.

Форма должна содержать два текстовых поля:
1. Ввод желаемого имени пользователя.
2. Пароль.

И две кнопки:
1. Создать (должна быть ``AcceptButton`` формы).
2. Отмена (должна быть ``CancelButton`` формы).

Также необходимо показать предупреждение о последствиях утраты пароля. В программе **MyMoney** был следующий текст:
```
Вы можете указать пароль, для защиты Вашей информации. 
Это актуально, если к Вашему компьютеру имеют доступ посторонние люди.
Обратите внимание, если Вы укажите пароль, то все данные будут шифроваться. 
При потере пароля, данные восстановить будет невозможно. 
Обязательно записывайте Ваш пароль.
```
(нужно будет подправить, и выкать маленькими буквами)

Имя пользователя будет использоваться в качестве имени файла профиля и его следует проверять на предмет наличия запрещенных символов (``Path.GetInvalidFileNameChars()``).

Пароль не является обязательным.

Длина пароля не должна превышать 24 символа.

При нажатии на кнопку «Создать» необходимо проверить уникальность имени пользователя. Сделать это можно при помощи метода ``MoneyBook.Core.User.Exists()``, указав базовый путь расположения файлов профилей пользователей (``Program.ProfileBasePath``) и имени создаваемого пользователя.

Если пользователь с указанным именем уже существует, то следует показать предупреждение и предложить ввести другое имя.

Если имя уникально, то для создания учетной записи необходимо вызвать метод ``MoneyBook.Core.User.Create()``, с передачей базового пути расположения файлов профилей пользователей (``Program.ProfileBasePath``) и указанных пользователем параметров учетной записи (имя, пароль).

В случае успеха, метод вернет экземпляр класса ``User``, используя который следует наполнить профиль пользователя данными по умолчанию:
* Список иконок (16x16);
* Список валют;
* Список типов счетов;
* Счет по умолчанию;
* Список статей расходов и доходов.

Данные по умолчанию должны находиться в ресурсах программы: ``Resources.DevaultValues`` (необходимо создать, это отдельная задача).

В момент создания профиля, элементы формы должны быть недоступны (``Enabled = False``). Пользователь не должен иметь возможность закрыть окно самостоятельно. При этом окно программы не должно казаться «замороженным», следует добавить индикатор отображения процесса создания профиля пользователя.

Созданный экземпляр пользователя следует передать в свойство ``Program.CurrentUser``.

После создания профиля, необходимо инициализировать и отобразить основное окно программы (``Main``). Окно регистрации должно быть автоматически закрыто.

**Comment by rdenysiuk** [comment]
или я пропустил или мы это не оговаривали названия Форм, кнопок и лейблов где будем хранить (ресурсы будем использовать)?

**Comment by alekseynemiro** [comment]
Да, ресурсы, уровня форм (стандартный механизм локализации).

Это в конце будем делать, когда все будет готово.

**Comment by alekseynemiro** [comment]
А значения по умолчанию общие, находятся в [Resources.DefaultValues](https://github.com/alekseynemiro/MoneyBook/tree/master/MoneyBook/Resources).

**Comment by rdenysiuk** [comment]
то есть сейчас все на русском, а потом будем все переводить?

и еще по поводу картинок для форм и кнопок: я часто пользуюсь http://www.fatcow.com/free-icons
будем эти использовать?

**Comment by alekseynemiro** [comment]
Да, делаем на русском, потом будет переводить. 

Сразу переводить не имеет смысла, это будет только все усложнять/замедлять, т.к. в процессе разработки могут быть изменения. Проще переводить, когда все будет готово. И мозг будет под работу с человеческими текстами адаптирован, а то при работе с кодом можно такого понаписать :-)

Иконки будут нужны. Нужно подбирать.

**Comment by alekseynemiro** [comment]
Иконки для значений по умолчанию должны быть в ``Resources.DefaultValues``.

А иконки уровня приложения - в общих ресурсах (Свойства проекта, вкладка Ресурсы)

**Comment by rdenysiuk** [comment]
пушнул свой первый коммит, посмотри правильно ли я понял тебя.

**Comment by alekseynemiro** [comment]
Да, вроде все правильно.


Вот только иконки на обычных кнопках наверное будут лишними. С локализацией и выравниванием будет много замутов.

Обычные кнопки (``Button``) лучше без иконок делать, только текст. 
Иконки хорошо пойдут для кнопок всяких ``ToolStrip`` и ``ContextMenu``.

**Comment by alekseynemiro** [comment]
Есть проблемы или нет времени? :-)

**Comment by rdenysiuk** [comment]
Да, чуток времени не хватает. Да и честно сказать я не ожидал что ты настолько быстро отреагировать на моё предложение о сотрудничестве. Надеюсь до следующей недели мои дела утрясутся и тогда буду выделять время для проекта.

**Comment by alekseynemiro** [comment]
Ok.

**Comment by alekseynemiro** [comment]
Форма **Login**  где-то затерялась. Есть ссылка на файл, но самого файла нет.
