### ISSUE TITLE
Иконки

### ISSUE THREAD

**Issue by alekseynemiro** [alekseynemiro/MoneyBook#5]
Понять, где и как хранить иконки (для категорий, счетов и т.п.).

**Comment by alekseynemiro** [comment]
Думаю, сделать набор иконок в базе.

**Comment by rdenysiuk** [comment]
Ты имеешь ввиду отдельную таблицу для иконок?
Или в каждой таблице будет поле в которое заганять массив байт?

**Comment by alekseynemiro** [comment]
Да, отдельную таблицу и там, где нужно указывать идентификаторы иконок.

В таблицу можно записать хеш-сумму файлов и проверять уникальность иконок, когда пользователь будет загружать свои изображения. Это позволит снизить объем данных. Хотя сама идея хранения бинарных данных в базе не очень хорошая, но выбора в данном случае нет. Один файл со всеми данными будет удобней, чем множество (даже если их собрать в архив, будет неудобно с временными файлами возиться).

В **MyMoney** иконки в виде **Base64** хранились, и могли добавляться для каждой отдельной записи, без проверки на дубликаты - плохое решение.

**Comment by rdenysiuk** [comment]
Только добавить ограничение по размеру иконки. Например максимальное разрешение 64х64

**Comment by alekseynemiro** [comment]
16x16 будет достаточно.
